name: Deploy Frontend to EC2

on:
  push:
    branches:
      - feat/#4

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prepare frontend build folder (flatten dist/)
        run: |
          mkdir -p frontend-build
          cp -r dist/* frontend-build/

      - name: Check frontend-build contents
        run: ls -al frontend-build

      - name: Deploy via SCP to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "frontend-build/*"
          target: "~/frontend-temp"

      - name: SSH into EC2 and move files with sudo
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            sudo mkdir -p /var/www/html
            sudo rm -rf /var/www/html/*
            sudo cp -r ~/frontend-temp/* /var/www/html/
            rm -rf ~/frontend-temp
